/**
 * Airline Data Constants
 *
 * Comprehensive list of airlines with their IATA 2-letter codes.
 * Used for searchable dropdown in Air Freight sheet builder.
 */

export interface AirlineData {
  name: string;
  code: string; // IATA 2-letter code
}

export const AIRLINES: AirlineData[] = [
  { code: "2B", name: "Albawings" },
  { code: "3K", name: "Jetstar Asia Airways" },
  { code: "3U", name: "Sichuan Airlines" },
  { code: "4M", name: "LATAM Argentina" },
  { code: "4U", name: "Germanwings" },
  { code: "5J", name: "Cebu Pacific" },
  { code: "5X", name: "UPS Airlines" },
  { code: "6E", name: "IndiGo" },
  { code: "7C", name: "Jeju Air" },
  { code: "7L", name: "Silk Way Airlines" },
  { code: "7W", name: "Wind Rose Aviation" },
  { code: "8M", name: "Myanmar Airways International" },
  { code: "9W", name: "Jet Airways" },
  { code: "AA", name: "American Airlines" },
  { code: "AC", name: "Air Canada" },
  { code: "AF", name: "Air France" },
  { code: "AI", name: "Air India" },
  { code: "AK", name: "AirAsia" },
  { code: "AM", name: "Aeromexico" },
  { code: "AR", name: "Aerolíneas Argentinas" },
  { code: "AS", name: "Alaska Airlines" },
  { code: "AT", name: "Royal Air Maroc" },
  { code: "AV", name: "Avianca" },
  { code: "AY", name: "Finnair" },
  { code: "AZ", name: "ITA Airways" },
  { code: "8D", name: "Fits Air" },
  { code: "B6", name: "JetBlue Airways" },
  { code: "B9", name: "Iran Air Tour" },
  { code: "BA", name: "British Airways" },
  { code: "BC", name: "Skymark Airlines" },
  { code: "BI", name: "Royal Brunei Airlines" },
  { code: "BL", name: "Pacific Airlines" },
  { code: "BR", name: "EVA Air" },
  { code: "BT", name: "airBaltic" },
  { code: "BW", name: "Caribbean Airlines" },
  { code: "BY", name: "TUI Airways" },
  { code: "CA", name: "Air China" },
  { code: "CI", name: "China Airlines" },
  { code: "CM", name: "Copa Airlines" },
  { code: "CX", name: "Cathay Pacific" },
  { code: "CZ", name: "China Southern Airlines" },
  { code: "D7", name: "AirAsia X" },
  { code: "DE", name: "Condor" },
  { code: "DL", name: "Delta Air Lines" },
  { code: "DY", name: "Norwegian Air Shuttle" },
  { code: "EI", name: "Aer Lingus" },
  { code: "EK", name: "Emirates" },
  { code: "ET", name: "Ethiopian Airlines" },
  { code: "EW", name: "Eurowings" },
  { code: "ER", name: "Serene Air" },
  { code: "EY", name: "Etihad Airways" },
  { code: "FD", name: "Thai AirAsia" },
  { code: "FJ", name: "Fiji Airways" },
  { code: "FX", name: "FedEx Express" },
  { code: "FZ", name: "flydubai" },
  { code: "G3", name: "GOL Linhas Aéreas" },
  { code: "G9", name: "Air Arabia" },
  { code: "GA", name: "Garuda Indonesia" },
  { code: "GF", name: "Gulf Air" },
  { code: "GK", name: "Jetstar Japan" },
  { code: "HA", name: "Hawaiian Airlines" },
  { code: "HM", name: "Air Seychelles" },
  { code: "HR", name: "Hahn Air" },
  { code: "HU", name: "Hainan Airlines" },
  { code: "HX", name: "Hong Kong Airways" },
  { code: "HY", name: "Uzbekistan Airways" },
  { code: "IB", name: "Iberia" },
  { code: "IK", name: "Air Kyrgyzstan" },
  { code: "IR", name: "Iran Air" },
  { code: "IY", name: "Yemenia" },
  { code: "J9", name: "Jazeera Airways" },
  { code: "JJ", name: "LATAM Brasil" },
  { code: "JL", name: "Japan Airlines" },
  { code: "JQ", name: "Jetstar Airways" },
  { code: "JU", name: "Air Serbia" },
  { code: "K6", name: "Cambodia Angkor Air" },
  { code: "KC", name: "Air Astana" },
  { code: "KE", name: "Korean Air" },
  { code: "KL", name: "KLM Royal Dutch Airlines" },
  { code: "KM", name: "Air Malta" },
  { code: "KQ", name: "Kenya Airways" },
  { code: "KU", name: "Kuwait Airways" },
  { code: "LA", name: "LATAM Airlines Chile" },
  { code: "LH", name: "Lufthansa" },
  { code: "LO", name: "LOT Polish Airlines" },
  { code: "LX", name: "Swiss International Air Lines" },
  { code: "LY", name: "El Al Israel Airlines" },
  { code: "M7", name: "MAS Air Cargo" },
  { code: "ME", name: "Middle East Airlines" },
  { code: "MF", name: "Xiamen Airlines" },
  { code: "MH", name: "Malaysia Airlines" },
  { code: "MI", name: "SilkAir" },
  { code: "MK", name: "Air Mauritius" },
  { code: "MS", name: "EgyptAir" },
  { code: "MT", name: "Thomas Cook Airlines" },
  { code: "MU", name: "China Eastern Airlines" },
  { code: "NH", name: "All Nippon Airways" },
  { code: "NX", name: "Air Macau" },
  { code: "NZ", name: "Air New Zealand" },
  { code: "OK", name: "Czech Airlines" },
  { code: "OM", name: "MIAT Mongolian Airlines" },
  { code: "OS", name: "Austrian Airlines" },
  { code: "OV", name: "Aurora Airlines" },
  { code: "OZ", name: "Asiana Airlines" },
  { code: "P4", name: "Air Peace" },
  { code: "PC", name: "Pegasus Airlines" },
  { code: "PE", name: "Air Panama" },
  { code: "PK", name: "Pakistan International Airlines" },
  { code: "PO", name: "Polar Air Cargo" },
  { code: "PR", name: "Philippine Airlines" },
  { code: "QF", name: "Qantas" },
  { code: "QR", name: "Qatar Airways" },
  { code: "R3", name: "Yakutia Airlines" },
  { code: "RA", name: "Nepal Airlines" },
  { code: "RJ", name: "Royal Jordanian" },
  { code: "RO", name: "TAROM" },
  { code: "S7", name: "S7 Airlines" },
  { code: "SA", name: "South African Airways" },
  { code: "SB", name: "Aircalin" },
  { code: "SG", name: "SpiceJet" },
  { code: "SK", name: "Scandinavian Airlines" },
  { code: "SN", name: "Brussels Airlines" },
  { code: "SQ", name: "Singapore Airlines" },
  { code: "SU", name: "Aeroflot" },
  { code: "SV", name: "Saudia" },
  { code: "T5", name: "Turkmenistan Airlines" },
  { code: "TA", name: "TACA International Airlines" },
  { code: "TC", name: "Air Tanzania" },
  { code: "TG", name: "Thai Airways" },
  { code: "TK", name: "Turkish Airlines" },
  { code: "TN", name: "Air Tahiti Nui" },
  { code: "TP", name: "TAP Air Portugal" },
  { code: "TR", name: "Scoot" },
  { code: "TW", name: "T'way Air" },
  { code: "UA", name: "United Airlines" },
  { code: "UL", name: "SriLankan Airlines" },
  { code: "UO", name: "Hong Kong Express Airways" },
  { code: "UR", name: "Uganda Airlines" },
  { code: "UX", name: "Air Europa" },
  { code: "VA", name: "Virgin Australia" },
  { code: "VI", name: "Vistara" },
  { code: "VN", name: "Vietnam Airlines" },
  { code: "VS", name: "Virgin Atlantic" },
  { code: "VT", name: "Air Tahiti" },
  { code: "VX", name: "Virgin America" },
  { code: "W4", name: "LC Peru" },
  { code: "W5", name: "Mahan Air" },
  { code: "WB", name: "RwandAir" },
  { code: "WN", name: "Southwest Airlines" },
  { code: "WS", name: "WestJet" },
  { code: "WY", name: "Oman Air" },
  { code: "X6", name: "Rainbow Aviation" },
  { code: "XJ", name: "Thai Lion Air" },
  { code: "XQ", name: "SunExpress" },
  { code: "XY", name: "flynas" },
  { code: "YM", name: "Montenegro Airlines" },
  { code: "ZH", name: "Shenzhen Airlines" },
  { code: "ABJ", name: "Abidjan" },
  { code: "ACC", name: "Kotoka International Airport" },
  { code: "ADD", name: "Addis Ababa" },
  { code: "AMD", name: "Sardar Vallabhbhai Patel International Airport" },
  { code: "AMS", name: "Amsterdam Schiphol Airport" },
  { code: "ARN", name: "Stockholm Arlanda" },
  { code: "ATL", name: "Atlanta" },
  { code: "AUH", name: "Abu Dhabi International Airport" },
  { code: "BCN", name: "Barcelona" },
  { code: "BKK", name: "Suvarnabhumi Airport" },
  { code: "BLQ", name: "Bologna" },
  { code: "BLR", name: "Kempegowda International Airport" },
  { code: "BNE", name: "Brisbane Airport" },
  { code: "BOM", name: "Mumbai (Chhatrapati Shivaji Intl.)" },
  { code: "BOM/MUM", name: "Chhatrapati Shivaji Maharaj International Airport" },
  { code: "BOS", name: "Boston" },
  { code: "BRU", name: "Brussels Airport" },
  { code: "CAI", name: "Cairo" },
  { code: "CCU", name: "Netaji Subhas Chandra Bose International Airport" },
  { code: "CDG", name: "Charles de Gaulle Airport" },
  { code: "CHC", name: "Christchurch Airport" },
  { code: "CKY", name: "Conakry" },
  { code: "CMB", name: "Bandaranaike International Airport" },
  { code: "CMN", name: "Casablanca" },
  { code: "COK", name: "Cochin International Airport" },
  { code: "DAC", name: "Hazrat Shahjalal International Airport" },
  { code: "DAR", name: "Dar Es Salaam" },
  { code: "DEL", name: "Indira Gandhi International Airport" },
  { code: "DFW", name: "Dallas/Fort Worth" },
  { code: "DKR", name: "Dakar" },
  { code: "DLA", name: "Douala" },
  { code: "DMM", name: "Dammam" },
  { code: "DOH", name: "Hamad International Airport" },
  { code: "DTW", name: "Detroit" },
  { code: "DXB", name: "Dubai International Airport" },
  { code: "ESB", name: "Ankara (Esenboğa)" },
  { code: "EWR", name: "Newark" },
  { code: "FCO", name: "Rome Fiumicino" },
  { code: "FIH", name: "Kinshasa" },
  { code: "FRA", name: "Frankfurt Airport" },
  { code: "GDL", name: "Guadalajara" },
  { code: "GRU", name: "São Paulo–Guarulhos International Airport" },
  { code: "HAN/SGN", name: "Hanoi / Ho Chi Minh City" },
  { code: "HEL", name: "Helsinki Airport" },
  { code: "HKG", name: "Hong Kong International Airport" },
  { code: "HRE", name: "Harare International Airport" },
  { code: "HYD", name: "Rajiv Gandhi International Airport" },
  { code: "IAH", name: "Houston (IAH)" },
  { code: "ICN", name: "Incheon International Airport" },
  { code: "IKA", name: "Imam Khomeini International Airport" },
  { code: "IST", name: "Istanbul Airport" },
  { code: "JED", name: "King Abdulaziz International Airport" },
  { code: "JFK", name: "John F. Kennedy International Airport" },
  { code: "JNB", name: "O.R. Tambo International Airport" },
  { code: "KGL", name: "Kigali" },
  { code: "KIX", name: "Osaka Kansai" },
  { code: "KRT", name: "Khartoum" },
  { code: "KUL", name: "Kuala Lumpur International Airport" },
  { code: "KWI", name: "Kuwait" },
  { code: "LAD", name: "Luanda" },
  { code: "LAX", name: "Los Angeles International Airport" },
  { code: "LED", name: "Pulkovo Airport" },
  { code: "LHR", name: "Heathrow Airport" },
  { code: "LIS", name: "Lisbon Airport" },
  { code: "LLW", name: "Lilongwe" },
  { code: "LOS", name: "Murtala Muhammed International Airport" },
  { code: "LUN", name: "Lusaka" },
  { code: "MAA", name: "Chennai International Airport" },
  { code: "MAD", name: "Madrid Barajas Airport" },
  { code: "MAN", name: "Manchester" },
  { code: "MCO", name: "Orlando" },
  { code: "MCT", name: "Muscat" },
  { code: "MEL", name: "Melbourne Airport" },
  { code: "MEM", name: "Memphis" },
  { code: "MEX", name: "Mexico City" },
  { code: "MEX/NLU", name: "Mexico City / Felipe Ángeles International Airport" },
  { code: "MIA", name: "Miami" },
  { code: "MLE", name: "Velana International Airport" },
  { code: "MNL", name: "Manila" },
  { code: "MPM", name: "Maputo" },
  { code: "MRU", name: "Sir Seewoosagur Ramgoolam International Airport" },
  { code: "MSQ", name: "Minsk National Airport" },
  { code: "MTY", name: "Monterrey" },
  { code: "MUC", name: "Munich Airport" },
  { code: "MXP", name: "Milan Malpensa" },
  { code: "NBO", name: "Jomo Kenyatta International Airport" },
  { code: "NRT", name: "Tokyo Narita" },
  { code: "NRT/HND", name: "Narita / Haneda" },
  { code: "NSI", name: "Yaoundé" },
  { code: "OPO", name: "Porto" },
  { code: "ORD", name: "O’Hare International Airport" },
  { code: "OTP", name: "Bucharest Henri Coandă Airport" },
  { code: "PEK", name: "Beijing" },
  { code: "PRG", name: "Prague" },
  { code: "PVG", name: "Shanghai Pudong" },
  { code: "PVG/PEK", name: "Shanghai Pudong / Beijing Capital" },
  { code: "RUH", name: "King Khalid International Airport" },
  { code: "SCL", name: "Santiago International Airport" },
  { code: "SEA", name: "Seattle" },
  { code: "SHJ", name: "Sharjah" },
  { code: "SIN", name: "Singapore Changi Airport" },
  { code: "SVO/DME/VKO", name: "Moscow Airports" },
  { code: "SYD", name: "Sydney Kingsford Smith Airport" },
  { code: "SZX", name: "Shenzhen" },
  { code: "TAO", name: "Qingdao" },
  { code: "TLV", name: "Ben Gurion Airport" },
  { code: "TPE", name: "Taoyuan International Airport" },
  { code: "TUN", name: "Tunis" },
  { code: "VCE/MXP", name: "Venice Marco Polo / Milan Malpensa" },
  { code: "VIE", name: "Vienna" },
  { code: "VNO", name: "Vilnius Airport" },
  { code: "WAW", name: "Warsaw Chopin Airport" },
  { code: "WDH", name: "Windhoek" },
  { code: "YUL", name: "Montreal" },
  { code: "YYC", name: "Calgary" },
  { code: "YYZ", name: "Toronto Pearson" },
  { code: "ZNZ", name: "Zanzibar" },
  { code: "ZRH", name: "Zurich Airport" }
];

/** O(1) lookup by IATA code (uppercase). */
export const AIRLINE_BY_CODE: Record<string, AirlineData> = Object.fromEntries(
  AIRLINES.map((a) => [a.code.toUpperCase(), a]),
);

/** O(1) lookup by airline name (lowercase). */
export const AIRLINE_BY_NAME: Record<string, AirlineData> = Object.fromEntries(
  AIRLINES.map((a) => [a.name.toLowerCase(), a]),
);

export function getAirlineByCode(code: string | null | undefined): AirlineData | undefined {
  if (!code) return undefined;
  return AIRLINE_BY_CODE[code.trim().toUpperCase()];
}

export function getAirlineByName(name: string | null | undefined): AirlineData | undefined {
  if (!name) return undefined;
  return AIRLINE_BY_NAME[name.trim().toLowerCase()];
}
